export const INITIAL_PRODUCTS = [
  {
    "id": "25-adet-kirmizi-gul-buketi",
    "name": "25 Adet Kırmızı Gül Buketi",
    "description": "25 Adet Kırmızı Gül Buketi - Taze ve şık aranjman.",
    "price": 7000,
    "old_price": 8400,
    "image_url": "/products/thumb_25-adet-kirmizi-gul-buketi-120-3548.webp",
    "stock": 50,
    "category": "Güller",
    "occasions": ["Geçmiş Olsun", "Sevgiliye", "Tebrik"],
    "is_featured": true
  },
  {
    "id": "mavi-cift-dalli-orkide",
    "name": "Mavi Çift Dallı Orkide",
    "description": "Mavi Çift Dallı Orkide - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_mavi-cift-dalli-orkide-149-6841.webp",
    "stock": 50,
    "category": "Orkide",
    "occasions": ["Yeni İş / Terfi", "Yeni Bebek", "Tebrik"],
    "is_featured": true
  },
  {
    "id": "vazoda-sari-ve-kirmizi-guller",
    "name": "Vazoda Sarı ve Kırmızı Güller",
    "description": "Vazoda Sarı ve Kırmızı Güller - Taze ve şık aranjman.",
    "price": 7899,
    "old_price": 9478,
    "image_url": "/products/thumb_vazoda-sari-ve-kirmizi-guller-70-4934.webp",
    "stock": 50,
    "category": "Güller",
    "occasions": ["Doğum Günü", "Tebrik"],
    "is_featured": true
  },
  {
    "id": "cam-fanusta-papatyalar",
    "name": "Cam Fanusta Papatyalar",
    "description": "Cam Fanusta Papatyalar - Taze ve şık aranjman.",
    "price": 1300,
    "old_price": 1560,
    "image_url": "/products/thumb_cam-fanusta-papatyalar-165-4358.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "occasions": ["Geçmiş Olsun", "Yeni Bebek"],
    "is_featured": false
  },
  {
    "id": "pembe-buyuk-gerbera-buketi",
    "name": "Pembe Büyük Gerbera Buketi",
    "description": "Pembe Büyük Gerbera Buketi - Taze ve şık aranjman.",
    "price": 2449,
    "old_price": 2938,
    "image_url": "/products/thumb_pembe-buyuk-gerbera-buketi-78-9304.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "occasions": ["Geçmiş Olsun", "Doğum Günü", "Yeni Bebek"],
    "is_featured": false
  },
  {
    "id": "areka-cicegi",
    "name": "Areka Çiçeği",
    "description": "Areka Çiçeği - Taze ve şık aranjman.",
    "price": 4100,
    "old_price": 4920,
    "image_url": "/products/thumb_areka-cicegi-164-1907.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "occasions": ["Yeni İş / Terfi", "Tebrik"],
    "is_featured": false
  },
  {
    "id": "soft-pembe-cicekli-celenk",
    "name": "Soft Pembe Çiçekli Çelenk",
    "description": "Soft Pembe Çiçekli Çelenk - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_soft-pembe-cicekli-celenk-139-3125.webp",
    "stock": 50,
    "category": "Çelenkler",
    "occasions": ["Tebrik", "Yeni İş / Terfi", "Doğum Günü"],
    "is_featured": false
  },
  {
    "id": "kutuda-19-adet-gul",
    "name": "Kutuda 19 Adet Gül",
    "description": "Kutuda 19 Adet Gül - Taze ve şık aranjman.",
    "price": 4200,
    "old_price": 5040,
    "image_url": "/products/thumb_kutuda-19-adet-gul-101-3458.webp",
    "stock": 50,
    "category": "Güller",
    "occasions": ["Yeni İş / Terfi", "Sevgiliye", "Doğum Günü"],
    "is_featured": true
  },
  {
    "id": "mercan-gul-buketi",
    "name": "Mercan Gül Buketi",
    "description": "Mercan Gül Buketi - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_mercan-gul-buketi-100-1933.webp",
    "stock": 50,
    "category": "Güller",
    "occasions": ["Sevgiliye", "Doğum Günü", "Tebrik"],
    "is_featured": true
  },
  {
    "id": "3-tane-gl-buketi",
    "name": "3 Tane Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 1500,
    "old_price": 1800,
    "image_url": "/products/thumb_3-tane-gul-buketi-24-7690.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "5-krmz-gl-buketi",
    "name": "5 Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 1750,
    "old_price": 2100,
    "image_url": "/products/thumb_5-kirmizi-gul-buketi-54-1257.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "6-tane-gl-buketi",
    "name": "6 Tane Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 1800,
    "old_price": 2160,
    "image_url": "/products/thumb_6-tane-gul-buketi-15-7092.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "6-pembe-gl-buketi",
    "name": "6 Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2000,
    "old_price": 2400,
    "image_url": "/products/thumb_6-pembe-gul-buketi-25-6558.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "byk-boy-pembe-karanfil-buketi",
    "name": "Büyük Boy Pembe Karanfil Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2000,
    "old_price": 2400,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "7-adet-gl-buketi-pembe-ve-krmz",
    "name": "7 Adet Gül Buketi Pembe ve Kırmızı",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2200,
    "old_price": 2640,
    "image_url": "/products/thumb_7-adet-gul-buketi-pembe-ve-kirmizi-53-4911.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "kutuda-sar-gerbera",
    "name": "Kutuda Sarı Gerbera",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2249,
    "old_price": 2348,
    "image_url": "/products/thumb_cam-fanusta-papatyalar-165-4358.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "17-pembe-karanfil-buketi",
    "name": "17 Pembe Karanfil Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2250,
    "old_price": 2700,
    "image_url": "/products/thumb_17-pembe-karanfil-buketi-126-2067.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "17-adet-beyaz-karanfil-buketi",
    "name": "17 Adet Beyaz Karanfil Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2250,
    "old_price": 2700,
    "image_url": "/products/thumb_17-adet-beyaz-karanfil-buketi-128-6726.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "7-gl-buketi",
    "name": "7 Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2350,
    "old_price": 2820,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "7-adet-beyaz-gl-buketi",
    "name": "7 Adet Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2350,
    "old_price": 2820,
    "image_url": "/products/thumb_7-adet-beyaz-gul-buketi-137-4419.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "pembe-byk-gerbera-buketi",
    "name": "Pembe Büyük Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2449,
    "old_price": 2548,
    "image_url": "/products/thumb_cam-fanusta-papatyalar-165-4358.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "mor-gerbera-buketi",
    "name": "Mor Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_mor-gerbera-buketi-22-9866.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "krmz-gerbera-buketi",
    "name": "Kırmızı Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_kirmizi-gerbera-buketi-34-7480.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "mor-karanfil-buketi",
    "name": "Mor Karanfil Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_mor-karanfil-buketi-35-1340.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "pembe-gerbera-buketi",
    "name": "Pembe Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_cam-fanusta-papatyalar-165-4358.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "karanfil-ve-gerbera-buketi",
    "name": "Karanfil ve Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_karanfil-ve-gerbera-buketi-38-9165.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "vazoda-renkli-gerbera",
    "name": "Vazoda Renkli Gerbera",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_vazoda-renkli-gerbera-48-978.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "vazoda-beyaz-ve-pembe-gerbera",
    "name": "Vazoda Beyaz ve Pembe Gerbera",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_cam-fanusta-papatyalar-165-4358.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "sar-gerbera-buketi",
    "name": "Sarı Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_sari-gerbera-buketi-55-8069.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "ayiekleri-buketleri",
    "name": "Ayçiçekleri Buketleri",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "gerek-ktkte-renkli-papatyalar",
    "name": "Gerçek Kütükte Renkli Papatyalar",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_gercek-kutukte-renkli-papatyalar-148-5842.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "krmz-antorium",
    "name": "Kırmızı Antorium",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2500,
    "old_price": 3000,
    "image_url": "/products/thumb_kirmizi-antorium-163-9986.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": false
  },
  {
    "id": "9-beyaz-gl-buketi",
    "name": "9 Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2700,
    "old_price": 3240,
    "image_url": "/products/thumb_9-beyaz-gul-buketi-135-8875.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "karanfil-ve-papatya-buketi",
    "name": "Karanfil ve Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_karanfil-ve-papatya-buketi-4-4885.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "vazoda-byk-boy-10-tane-gl",
    "name": "Vazoda Büyük Boy 10 Tane Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_vazoda-buyuk-boy-10-tane-gul-9-4582.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "10-tane-krmz-beyaz-gl-buketi",
    "name": "10 Tane Kırmızı Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "mavi-ift-dall-orkide",
    "name": "Mavi Çift Dallı Orkide",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_mavi-cift-dalli-orkide-149-1530.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": false
  },
  {
    "id": "seramik-vazoda-ift-dall-beyaz-orkideler",
    "name": "Seramik Vazoda Çift Dallı Beyaz Orkideler",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_seramik-vazoda-cift-dalli-beyaz-orkideler-160-735.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": false
  },
  {
    "id": "cam-vazoda-ssl-orkideler",
    "name": "Cam Vazoda Süslü Orkideler",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_cam-vazoda-suslu-orkideler-161-6778.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": false
  },
  {
    "id": "ift-dall-mor-orkide",
    "name": "Çift Dallı Mor Orkide",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2750,
    "old_price": 3300,
    "image_url": "/products/thumb_cift-dalli-mor-orkide-166-3125.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": false
  },
  {
    "id": "10-adet-premium-beyaz-gl-buketi",
    "name": "10 Adet Premium Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2850,
    "old_price": 3420,
    "image_url": "/products/thumb_10-adet-premium-beyaz-gul-buketi-88-6477.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "10-tane-beyaz-gl-buketi",
    "name": "10 Tane Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2899,
    "old_price": 3478.8,
    "image_url": "/products/thumb_10-tane-beyaz-gul-buketi-14-3450.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "10-tane-gll-buket",
    "name": "10 Tane Güllü Buket",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 2900,
    "old_price": 3480,
    "image_url": "/products/thumb_10-tane-gullu-buket-23-6742.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "12-tane-krmz-gl-buketi",
    "name": "12 Tane Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3000,
    "old_price": 3600,
    "image_url": "/products/thumb_12-tane-kirmizi-gul-buketi-13-3621.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "12-adet-krmz-beyaz-gl-buketi",
    "name": "12 Adet Kırmızı Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3000,
    "old_price": 3600,
    "image_url": "/products/thumb_12-adet-kirmizi-beyaz-gul-buketi-57-7359.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "vazoda-12-beyaz-gl-buketi",
    "name": "Vazoda 12 Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3000,
    "old_price": 3600,
    "image_url": "/products/thumb_vazoda-12-beyaz-gul-buketi-63-5021.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "vazoda-12-tane-beyaz-gl",
    "name": "Vazoda 12 Tane Beyaz Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3000,
    "old_price": 3600,
    "image_url": "/products/thumb_vazoda-12-tane-beyaz-gul-75-6246.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "mor-kasmpat-buketi",
    "name": "Mor Kasımpatı Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3000,
    "old_price": 3600,
    "image_url": "/products/thumb_mor-kasimpati-buketi-99-3387.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "9-beyaz-gl-premium-buket",
    "name": "9 Beyaz Gül Premium Buket",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3000,
    "old_price": 3600,
    "image_url": "/products/thumb_9-beyaz-gul-premium-buket-134-2684.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "kutuda-15-pembe-gl-ve-papatyalar",
    "name": "Kutuda 15 Pembe Gül ve Papatyalar",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3250,
    "old_price": 3900,
    "image_url": "/products/thumb_kutuda-15-pembe-gul-ve-papatyalar-102-7123.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "ift-dal-orkideli-bahar-aranjman",
    "name": "Çift Dal Orkideli Bahar Aranjmanı",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3250,
    "old_price": 3900,
    "image_url": "/products/thumb_cift-dal-orkideli-bahar-aranjmani-158-1681.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": false
  },
  {
    "id": "vazoda-12-tane-pembe-gller",
    "name": "Vazoda 12 Tane Pembe Güller",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3300,
    "old_price": 3960,
    "image_url": "/products/thumb_vazoda-12-tane-pembe-guller-39-769.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "12-adet-gl-buketi",
    "name": "12 Adet Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3300,
    "old_price": 3960,
    "image_url": "/products/thumb_12-adet-gul-buketi-59-2978.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "11-beyaz-gl-buketi",
    "name": "11 Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3300,
    "old_price": 3960,
    "image_url": "/products/thumb_11-beyaz-gul-buketi-133-8892.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": false
  },
  {
    "id": "turuncu-gerbera-buketi",
    "name": "Turuncu Gerbera Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_cam-fanusta-papatyalar-165-4358.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "mor-ve-beyaz-papatya-buketi",
    "name": "Mor ve Beyaz Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_mor-ve-beyaz-papatya-buketi-98-8304.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "soft-pembe-iekli-elenk",
    "name": "Soft Pembe Çiçekli Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_soft-pembe-cicekli-celenk-139-8257.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": false
  },
  {
    "id": "beyaz-soft-grnml-elenk",
    "name": "Beyaz Soft Görünümlü Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_beyaz-soft-gorunumlu-celenk-140-3262.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": false
  },
  {
    "id": "krmz-uygun-fiyatl-elenk",
    "name": "Kırmızı Uygun Fiyatlı Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_kirmizi-uygun-fiyatli-celenk-141-6789.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": false
  },
  {
    "id": "sar-ve-krmz-elenk",
    "name": "Sarı ve Kırmızı Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_sari-ve-kirmizi-celenk-142-1522.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": false
  },
  {
    "id": "difenbahya-tropik",
    "name": "Difenbahya Tropik",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_difenbahya-tropik-143-7121.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": false
  },
  {
    "id": "3l-yucca-iei",
    "name": "3'lü Yucca Çiçeği",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3500,
    "old_price": 4200,
    "image_url": "/products/thumb_3-lu-yucca-cicegi-155-6289.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": false
  },
  {
    "id": "areka-iei",
    "name": "Areka Çiçeği",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3650,
    "old_price": 4380,
    "image_url": "/products/thumb_areka-cicegi-164-1907.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": false
  },
  {
    "id": "pembe-karanfil-buketi",
    "name": "Pembe Karanfil Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3700,
    "old_price": 4440,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "papatya-ve-mor-kasmpat-buketi",
    "name": "Papatya ve Mor Kasımpatı Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3700,
    "old_price": 4440,
    "image_url": "/products/thumb_papatya-ve-mor-kasimpati-buketi-96-5814.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "mor-ve-sar-papatya-buketi",
    "name": "Mor ve Sarı Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3700,
    "old_price": 4440,
    "image_url": "/products/thumb_mor-ve-sari-papatya-buketi-97-7245.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": false
  },
  {
    "id": "15-adet-renkli-kasmpat",
    "name": "15 Adet Renkli Kasımpatı",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3750,
    "old_price": 4500,
    "image_url": "/products/thumb_15-adet-renkli-kasimpati-131-9868.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": false
  },
  {
    "id": "ayakl-sepet-krmz-iekli-elenk",
    "name": "Ayaklı Sepet Kırmızı Çiçekli Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3750,
    "old_price": 4500,
    "image_url": "/products/thumb_ayakli-sepet-kirmizi-cicekli-celenk-152-617.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": false
  },
  {
    "id": "ift-dall-beyaz-orkide-ve-7-adet-gl",
    "name": "Çift Dallı Beyaz Orkide ve 7 Adet Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 3750,
    "old_price": 4500,
    "image_url": "/products/thumb_cift-dalli-beyaz-orkide-ve-7-adet-gul-162-4741.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": false
  },
  {
    "id": "beyaz-gerbera-elenk",
    "name": "Beyaz Gerbera Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4000,
    "old_price": 4800,
    "image_url": "/products/thumb_beyaz-gerbera-celenk-154-5130.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": false
  },
  {
    "id": "kutuda-19-adet-gl",
    "name": "Kutuda 19 Adet Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4200,
    "old_price": 5040,
    "image_url": "/products/thumb_kutuda-19-adet-gul-101-5423.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-15-tane-krmz-beyaz-gller",
    "name": "Vazoda 15 Tane Kırmızı Beyaz Güller",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4250,
    "old_price": 5100,
    "image_url": "/products/thumb_vazoda-15-tane-kirmizi-beyaz-guller-29-8278.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-18-tane-pembe-gl",
    "name": "Vazoda 18 Tane Pembe Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_vazoda-18-tane-pembe-gul-12-8682.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-15-beyaz-gl",
    "name": "Vazoda 15 Beyaz Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_vazoda-15-beyaz-gul-32-500.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-20-ayiekleri",
    "name": "Vazoda 20 Ayçiçekleri",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_vazoda-20-aycicekleri-60-7573.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "renkli-buket",
    "name": "Renkli Buket",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "mercan-gl-buketi",
    "name": "Mercan Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_mercan-gul-buketi-100-9364.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "eustoma-buketi",
    "name": "Eustoma Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_eustoma-buketi-103-6001.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "15-byk-boy-krmz-gl-buketi",
    "name": "15 Büyük Boy Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_15-buyuk-boy-kirmizi-gul-buketi-130-564.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "15-adet-gl-buketi-pembe-katta",
    "name": "15 Adet Gül Buketi Pembe Kağıtta",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_15-adet-gul-buketi-pembe-kagitta-132-2389.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "2-katl-dn-iei-elenk",
    "name": "2 Katlı Düğün Çiçeği Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_2-katli-dugun-cicegi-celenk-150-1718.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": true
  },
  {
    "id": "pembe-iekler-ile-elenk",
    "name": "Pembe Çiçekler ile Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4500,
    "old_price": 5400,
    "image_url": "/products/thumb_pembe-cicekler-ile-celenk-153-5598.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": true
  },
  {
    "id": "pembe-ve-krmz-krizantem-buketi",
    "name": "Pembe ve Kırmızı Krizantem Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4750,
    "old_price": 5700,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "17-krmz-ve-beyaz-gl-buketi",
    "name": "17 Kırmızı ve Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 4750,
    "old_price": 5700,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "25-tane-gl-buketi",
    "name": "25 Tane Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5250,
    "old_price": 6300,
    "image_url": "/products/thumb_25-tane-gul-buketi-19-2408.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "kraft-katta-papatya-buketi",
    "name": "Kraft Kağıtta Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_kraft-kagitta-papatya-buketi-1-1354.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": true
  },
  {
    "id": "20-tane-beyaz-gl-buketi",
    "name": "20 Tane Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_20-tane-beyaz-gul-buketi-58-9119.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-35-tane-beyaz-gller",
    "name": "Vazoda 35 Tane Beyaz Güller",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_vazoda-35-tane-beyaz-guller-52-6629.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-20-beyaz-gl",
    "name": "Vazoda 20 Beyaz Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_vazoda-20-beyaz-gul-65-5077.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-20-pembe-gl",
    "name": "Vazoda 20 Pembe Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_vazoda-20-pembe-gul-74-1794.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "pembe-ortanca-ssl-buket",
    "name": "Pembe Ortanca Süslü Buket",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "kraton",
    "name": "Kraton",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_kraton-157-9253.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": true
  },
  {
    "id": "4l-yuka-iei",
    "name": "4'lü Yuka Çiçeği",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5500,
    "old_price": 6600,
    "image_url": "/products/thumb_4-lu-yuka-cicegi-159-5078.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": true
  },
  {
    "id": "19-gl-buketi",
    "name": "19 Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5700,
    "old_price": 6840,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "21-beyaz-gl-buketi",
    "name": "21 Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5750,
    "old_price": 6900,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "21-adet-krem-gl-buketi",
    "name": "21 Adet Krem Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5750,
    "old_price": 6900,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "3-pembe-gl-buketi",
    "name": "3 Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5750,
    "old_price": 6900,
    "image_url": "/products/thumb_3-pembe-gul-buketi-138-2529.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "25-tane-krmz-gl-buketi",
    "name": "25 Tane Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5899,
    "old_price": 7078.8,
    "image_url": "/products/thumb_25-tane-kirmizi-gul-buketi-8-6013.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "31-adet-krmz-gl-buketi",
    "name": "31 Adet Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5900,
    "old_price": 7080,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "21-adet-krmz-gl-buketi",
    "name": "21 Adet Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 5900,
    "old_price": 7080,
    "image_url": "/products/thumb_21-adet-kirmizi-gul-buketi-124-3963.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "24-tane-sar-gl-buketi",
    "name": "24 Tane Sarı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6000,
    "old_price": 7200,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "sar-ve-krmz-buket",
    "name": "Sarı ve Kırmızı Buket",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6000,
    "old_price": 7200,
    "image_url": "/products/thumb_sari-ve-kirmizi-buket-90-1256.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "beyaz-ve-mor-papatya-buketi",
    "name": "Beyaz ve Mor Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6000,
    "old_price": 7200,
    "image_url": "/products/thumb_beyaz-ve-mor-papatya-buketi-105-4819.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": true
  },
  {
    "id": "25-tane-beyaz-gl-buketi",
    "name": "25 Tane Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6250,
    "old_price": 7500,
    "image_url": "/products/thumb_25-tane-beyaz-gul-buketi-10-1549.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-25-beyaz-gl",
    "name": "Vazoda 25 Beyaz Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6250,
    "old_price": 7500,
    "image_url": "/products/thumb_vazoda-25-beyaz-gul-31-6496.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "byk-papatya-buketi",
    "name": "Büyük Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6350,
    "old_price": 7620,
    "image_url": "/products/thumb_buyuk-papatya-buketi-104-4835.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": true
  },
  {
    "id": "papatya-ve-pembe-gl-buketi",
    "name": "Papatya ve Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6500,
    "old_price": 7800,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-byk-lilyumlar",
    "name": "Vazoda Büyük Lilyumlar",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6500,
    "old_price": 7800,
    "image_url": "/products/thumb_vazoda-buyuk-lilyumlar-26-3210.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "vazoda-byk-boy-lilyum",
    "name": "Vazoda Büyük Boy Lilyum",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6500,
    "old_price": 7800,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "premium-lilyum-buketleri",
    "name": "Premium Lilyum Buketleri",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6500,
    "old_price": 7800,
    "image_url": "/products/thumb_premium-lilyum-buketleri-44-195.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "4-kk-massengena-iei",
    "name": "4 kök Massengena Çiçeği",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 6500,
    "old_price": 7800,
    "image_url": "/products/thumb_4-kok-massengena-cicegi-156-6035.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": true
  },
  {
    "id": "25-byk-boy-krmz-gl-buketi",
    "name": "25 Büyük Boy Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7000,
    "old_price": 8400,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "25-adet-krmz-gl-buketi",
    "name": "25 Adet Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7000,
    "old_price": 8400,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "25-adet-beyaz-gl-buketi",
    "name": "25 Adet Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7000,
    "old_price": 8400,
    "image_url": "/products/thumb_25-adet-beyaz-gul-buketi-121-6968.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "jumbo-boy-orkideler",
    "name": "Jumbo Boy Orkideler",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7000,
    "old_price": 8400,
    "image_url": "/products/thumb_jumbo-boy-orkideler-146-6911.webp",
    "stock": 50,
    "category": "Orkide",
    "is_featured": true
  },
  {
    "id": "vazoda-30-tane-gl-buketi",
    "name": "Vazoda 30 Tane Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_vazoda-30-tane-gul-buketi-7-8168.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "pembe-ve-krmz-gl-buketleri",
    "name": "Pembe ve Kırmızı Gül Buketleri",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_pembe-ve-kirmizi-gul-buketleri-11-6522.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "35-tane-gl-buketi",
    "name": "35 Tane Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_35-tane-gul-buketi-18-8943.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "mor-gl-buketi",
    "name": "Mor Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_mor-gul-buketi-28-9818.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-beyaz-lilyumlar",
    "name": "Vazoda Beyaz Lilyumlar",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_vazoda-beyaz-lilyumlar-43-339.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "lilyum-ve-pembe-gl-buketi",
    "name": "Lilyum ve Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "seni-seviyorum-buketi",
    "name": "Seni Seviyorum Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7500,
    "old_price": 9000,
    "image_url": "/products/thumb_seni-seviyorum-buketi-89-3156.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "byk-boy-ficus-benjamin",
    "name": "Büyük Boy Ficus Benjamin",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 7900,
    "old_price": 9480,
    "image_url": "/products/thumb_buyuk-boy-ficus-benjamin-144-6853.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": true
  },
  {
    "id": "pembe-kasmpat-buketi",
    "name": "Pembe Kasımpatı Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 8000,
    "old_price": 9600,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "15-krmz-gl-16-beyaz-gl-buketi",
    "name": "15 Kırmızı Gül 16 Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 8250,
    "old_price": 9900,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "35-tane-pembe-gl-buketi",
    "name": "35 Tane Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 8500,
    "old_price": 10200,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "seramikte-renkli-iekler",
    "name": "Seramikte Renkli Çiçekler",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 8500,
    "old_price": 10200,
    "image_url": "/products/thumb_seramikte-renkli-cicekler-147-5492.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "ylba-iei-kokina-aranjman",
    "name": "Yılbaşı Çiçeği Kokina Aranjman",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 8500,
    "old_price": 8649,
    "image_url": "/products/thumb_kirmizi-antorium-163-9986.webp",
    "stock": 50,
    "category": "Saksı Çiçekleri",
    "is_featured": true
  },
  {
    "id": "byk-pembe-gl-buketi",
    "name": "Büyük Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 8999,
    "old_price": 10798.8,
    "image_url": "/products/thumb_buyuk-pembe-gul-buketi-27-9874.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "50-adet-pembe-gl-buketi",
    "name": "50 Adet Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9000,
    "old_price": 10800,
    "image_url": "/products/thumb_50-adet-pembe-gul-buketi-36-512.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "byk-sar-katta-papatya-buketi",
    "name": "Büyük Sarı Kağıtta Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9500,
    "old_price": 11400,
    "image_url": "/products/thumb_buyuk-sari-kagitta-papatya-buketi-2-7909.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": true
  },
  {
    "id": "51-adet-papatya-buketi",
    "name": "51 Adet Papatya Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9500,
    "old_price": 11400,
    "image_url": "/products/thumb_51-adet-papatya-buketi-111-8911.webp",
    "stock": 50,
    "category": "Papatya / Gerbera",
    "is_featured": true
  },
  {
    "id": "35-adet-gl-buketi",
    "name": "35 Adet Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9750,
    "old_price": 11700,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "renkli-premium-buket",
    "name": "Renkli Premium Buket",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_buyuk-boy-pembe-karanfil-buketi-40-4519.webp",
    "stock": 50,
    "category": "Buketler",
    "is_featured": true
  },
  {
    "id": "premium-gl-buketi",
    "name": "Premium Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "40-tane-premium-gl-buketi",
    "name": "40 Tane Premium Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_40-tane-premium-gul-buketi-17-9036.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-pembe-lilyum-ve-krmz-gller",
    "name": "Vazoda Pembe Lilyum ve Kırmızı Güller",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_vazoda-pembe-lilyum-ve-kirmizi-guller-33-8778.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-35-tane-krmz-gl",
    "name": "Vazoda 35 Tane Kırmızı Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_vazoda-35-tane-kirmizi-gul-42-1459.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "50-tane-pembe-gl-buketi",
    "name": "50 Tane Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-40-tane-sar-gl",
    "name": "Vazoda 40 Tane Sarı Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_vazoda-40-tane-sari-gul-51-8603.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "pembe-and-beyaz-gl-buketi",
    "name": "Pembe and Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-40-tane-4-renkli-gller",
    "name": "Vazoda 40 Tane 4 Renkli Güller",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_vazoda-40-tane-4-renkli-guller-68-8773.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "40-tane-pembe-gl-buketi",
    "name": "40 Tane Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "51-adet-pembe-gl-buketi",
    "name": "51 Adet Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "51-adet-pembe-ve-krem-gl-buketi",
    "name": "51 Adet Pembe ve Krem Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "51-adet-krem-gl-buketi",
    "name": "51 Adet Krem Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "51-adet-krmz-gl-buketi",
    "name": "51 Adet Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "51-adet-byk-boy-krmz-gl-buketi",
    "name": "51 Adet Büyük Boy Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "51-adet-beyaz-gl-buketi",
    "name": "51 Adet Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_51-adet-beyaz-gul-buketi-115-8785.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "29-krmz-gl-ve-12-beyaz-gl-buketi",
    "name": "29 Kırmızı Gül ve 12 Beyaz Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 9899,
    "old_price": 11878.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "41-tane-byk-boy-krmz-gl-buketi",
    "name": "41 Tane Büyük Boy Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 11898,
    "old_price": 14277.6,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "pembe-beyaz-ve-krmz-gl-buketi",
    "name": "Pembe - Beyaz ve Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 11900,
    "old_price": 14280,
    "image_url": "/products/thumb_pembe-beyaz-ve-kirmizi-gul-buketi-41-4972.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "kutuda-41-beyaz-gller",
    "name": "Kutuda 41 Beyaz Güller",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 11989,
    "old_price": 14386.8,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "50-tane-byk-gl-buketi",
    "name": "50 Tane Büyük Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 12000,
    "old_price": 14400,
    "image_url": "/products/thumb_50-tane-buyuk-gul-buketi-20-7066.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "premium-50-tane-pembe-gl-buketi",
    "name": "Premium 50 Tane Pembe Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 12000,
    "old_price": 14400,
    "image_url": "/products/thumb_premium-50-tane-pembe-gul-buketi-21-2678.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "40-tane-beyaz-gl-ve-ayck",
    "name": "40 Tane Beyaz Gül ve Ayıcık",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 12000,
    "old_price": 14400,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "50-krmz-gl-buketi",
    "name": "50 Kırmızı Gül Buketi",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 12000,
    "old_price": 14400,
    "image_url": "/products/thumb_50-kirmizi-gul-buketi-64-2995.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "vazoda-40-tane-gl",
    "name": "Vazoda 40 Tane Gül",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 12000,
    "old_price": 14400,
    "image_url": "/products/thumb_7-gul-buketi-136-9049.webp",
    "stock": 50,
    "category": "Güller",
    "is_featured": true
  },
  {
    "id": "panolu-gsterili-elenk",
    "name": "Panolu Gösterişli Çelenk",
    "description": "${name} - Taze ve şık aranjman.",
    "price": 12000,
    "old_price": 14400,
    "image_url": "/products/thumb_panolu-gosterisli-celenk-151-4461.webp",
    "stock": 50,
    "category": "Çelenkler",
    "is_featured": true
  }
];